apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fetch-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/fetch/clickhouse/host
    secretKey: CLICKHOUSE_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/fetch/clickhouse/user
    secretKey: CLICKHOUSE_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/fetch/clickhouse/pass
    secretKey: CLICKHOUSE_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/fetch/s3/access_key_id
    secretKey: S3_AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/fetch/s3/secret_access_key
    secretKey: S3_AWS_SECRET_ACCESS_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "fetch-api.fullname" . }}-secret
    template:
      metadata: {}
