// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/DIMO-Network/cloudevent"
)

// Filter for cloud event queries.
type CloudEventFilter struct {
	ID          *string    `json:"id,omitempty"`
	Type        *string    `json:"type,omitempty"`
	DataVersion *string    `json:"dataVersion,omitempty"`
	Source      *string    `json:"source,omitempty"`
	Producer    *string    `json:"producer,omitempty"`
	Before      *time.Time `json:"before,omitempty"`
	After       *time.Time `json:"after,omitempty"`
}

// Cloud event index entry: typed header + storage key.
type CloudEventIndex struct {
	Header   *cloudevent.CloudEventHeader `json:"header"`
	IndexKey string                       `json:"indexKey"`
}

// The root query type for the Fetch API GraphQL schema. ERC721 DID (e.g. did:eth:chainId:contract:tokenId).
type Query struct {
}
