// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/DIMO-Network/cloudevent"
)

// Filter for cloud event queries.
type CloudEventFilter struct {
	ID          *string    `json:"id,omitempty"`
	Type        *string    `json:"type,omitempty"`
	Dataversion *string    `json:"dataversion,omitempty"`
	Source      *string    `json:"source,omitempty"`
	Producer    *string    `json:"producer,omitempty"`
	Before      *time.Time `json:"before,omitempty"`
	After       *time.Time `json:"after,omitempty"`
}

// Cloud event index entry: typed header + storage key.
type CloudEventIndex struct {
	Header   *cloudevent.CloudEventHeader `json:"header"`
	IndexKey string                       `json:"indexKey"`
}

// Summary of a single cloud event type for a subject.
type CloudEventTypeSummary struct {
	// Cloud event type string (e.g. "dimo.status").
	Type string `json:"type"`
	// Number of cloud events of this type.
	Count int `json:"count"`
	// Earliest event timestamp.
	FirstSeen time.Time `json:"firstSeen"`
	// Latest event timestamp.
	LastSeen time.Time `json:"lastSeen"`
}

// The root query type for the Fetch API GraphQL schema. ERC721 DID (e.g. did:eth:chainId:contract:tokenId).
type Query struct {
}
