// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: pkg/grpc/fetch-api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchOptions provides filtering options to narrow down the search results for objects
// based on various criteria. If a field is not set, it is not used for filtering.
type SearchOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Only include events after this timestamp.
	After *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	// Only include events before this timestamp.
	Before *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	// Whether to sort results in ascending order by timestamp.
	TimestampAsc *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=timestamp_asc,json=timestampAsc,proto3" json:"timestamp_asc,omitempty"`
	// Type of the event to filter.
	Type *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// DataVersion of the event to filter.
	DataVersion *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	// The subject of the event to filter.
	Subject *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// The source identifier responsible for creating the data.
	Source *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	// The producer of the data, source entity responsible for creating the data.
	Producer *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=producer,proto3" json:"producer,omitempty"`
	// Additional optional metadata for more precise filtering.
	Optional *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=optional,proto3" json:"optional,omitempty"`
}

func (x *SearchOptions) Reset() {
	*x = SearchOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOptions) ProtoMessage() {}

func (x *SearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOptions.ProtoReflect.Descriptor instead.
func (*SearchOptions) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{0}
}

func (x *SearchOptions) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *SearchOptions) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *SearchOptions) GetTimestampAsc() *wrapperspb.BoolValue {
	if x != nil {
		return x.TimestampAsc
	}
	return nil
}

func (x *SearchOptions) GetType() *wrapperspb.StringValue {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SearchOptions) GetDataVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.DataVersion
	}
	return nil
}

func (x *SearchOptions) GetSubject() *wrapperspb.StringValue {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *SearchOptions) GetSource() *wrapperspb.StringValue {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SearchOptions) GetProducer() *wrapperspb.StringValue {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *SearchOptions) GetOptional() *wrapperspb.StringValue {
	if x != nil {
		return x.Optional
	}
	return nil
}

type CloudEventMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The cloud event header of the cloud event.
	Header *CloudEventHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The index key of the cloud event.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CloudEventMetadata) Reset() {
	*x = CloudEventMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudEventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEventMetadata) ProtoMessage() {}

func (x *CloudEventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEventMetadata.ProtoReflect.Descriptor instead.
func (*CloudEventMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{1}
}

func (x *CloudEventMetadata) GetHeader() *CloudEventHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CloudEventMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetLatestMetadataRequest includes search options to filter the events.
type GetLatestMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *SearchOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GetLatestMetadataRequest) Reset() {
	*x = GetLatestMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestMetadataRequest) ProtoMessage() {}

func (x *GetLatestMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetLatestMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestMetadataRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetLatestMetadataResponse provides the latest metadata retrieved for the specified search criteria.
type GetLatestMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The latest index key retrieved for the specified search criteria.
	Metadata *CloudEventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *GetLatestMetadataResponse) Reset() {
	*x = GetLatestMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestMetadataResponse) ProtoMessage() {}

func (x *GetLatestMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetLatestMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestMetadataResponse) GetMetadata() *CloudEventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListMetadataRequest includes search options to filter the events.
type ListMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Search options to filter the events.
	Options *SearchOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// The maximum number of metadata objects to return.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListMetadataRequest) Reset() {
	*x = ListMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataRequest) ProtoMessage() {}

func (x *ListMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataRequest.ProtoReflect.Descriptor instead.
func (*ListMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListMetadataRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListMetadataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListMetadataResponse returns the list of metadata for cloud events retrieved for the specified search criteria.
type ListMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of metadata objects retrieved for the specified search criteria.
	MetadataList []*CloudEventMetadata `protobuf:"bytes,1,rep,name=metadata_list,json=metadataList,proto3" json:"metadata_list,omitempty"`
}

func (x *ListMetadataResponse) Reset() {
	*x = ListMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataResponse) ProtoMessage() {}

func (x *ListMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataResponse.ProtoReflect.Descriptor instead.
func (*ListMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListMetadataResponse) GetMetadataList() []*CloudEventMetadata {
	if x != nil {
		return x.MetadataList
	}
	return nil
}

// GetLatestCloudEventRequest includes search options to filter the events.
type GetLatestCloudEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Search options to filter the events.
	Options *SearchOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *GetLatestCloudEventRequest) Reset() {
	*x = GetLatestCloudEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestCloudEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCloudEventRequest) ProtoMessage() {}

func (x *GetLatestCloudEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCloudEventRequest.ProtoReflect.Descriptor instead.
func (*GetLatestCloudEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestCloudEventRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetLatestCloudEventResponse provides the data retrieved from the latest cloud event.
type GetLatestCloudEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The data retrieved from the latest cloud event.
	CloudEvent *CloudEvent `protobuf:"bytes,1,opt,name=cloud_event,json=cloudEvent,proto3" json:"cloud_event,omitempty"`
}

func (x *GetLatestCloudEventResponse) Reset() {
	*x = GetLatestCloudEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestCloudEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCloudEventResponse) ProtoMessage() {}

func (x *GetLatestCloudEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCloudEventResponse.ProtoReflect.Descriptor instead.
func (*GetLatestCloudEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetLatestCloudEventResponse) GetCloudEvent() *CloudEvent {
	if x != nil {
		return x.CloudEvent
	}
	return nil
}

// ListCloudEventsRequest includes search options to filter the events.
type ListCloudEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Search options to filter the events.
	Options *SearchOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// The maximum number of objects to return.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListCloudEventsRequest) Reset() {
	*x = ListCloudEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCloudEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudEventsRequest) ProtoMessage() {}

func (x *ListCloudEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudEventsRequest.ProtoReflect.Descriptor instead.
func (*ListCloudEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListCloudEventsRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListCloudEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListCloudEventsResponse provides the list of data retrieved from the objects.
type ListCloudEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of data retrieved from the objects.
	CloudEvents []*CloudEvent `protobuf:"bytes,1,rep,name=cloud_events,json=cloudEvents,proto3" json:"cloud_events,omitempty"`
}

func (x *ListCloudEventsResponse) Reset() {
	*x = ListCloudEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCloudEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudEventsResponse) ProtoMessage() {}

func (x *ListCloudEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudEventsResponse.ProtoReflect.Descriptor instead.
func (*ListCloudEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListCloudEventsResponse) GetCloudEvents() []*CloudEvent {
	if x != nil {
		return x.CloudEvents
	}
	return nil
}

// ListCloudEventsFromKeysRequest includes the index key to filter the events.
type ListCloudEventsFromKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The index_keys that will be retrieved.
	IndexKeys []string `protobuf:"bytes,1,rep,name=index_keys,json=indexKeys,proto3" json:"index_keys,omitempty"`
}

func (x *ListCloudEventsFromKeysRequest) Reset() {
	*x = ListCloudEventsFromKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCloudEventsFromKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudEventsFromKeysRequest) ProtoMessage() {}

func (x *ListCloudEventsFromKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudEventsFromKeysRequest.ProtoReflect.Descriptor instead.
func (*ListCloudEventsFromKeysRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListCloudEventsFromKeysRequest) GetIndexKeys() []string {
	if x != nil {
		return x.IndexKeys
	}
	return nil
}

// ListCloudEventsFromNameResponse provides the list of data retrieved from the objects.
type ListCloudEventsFromKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of data retrieved from the objects.
	CloudEvents []*CloudEvent `protobuf:"bytes,1,rep,name=cloud_events,json=cloudEvents,proto3" json:"cloud_events,omitempty"`
}

func (x *ListCloudEventsFromKeysResponse) Reset() {
	*x = ListCloudEventsFromKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fetch_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCloudEventsFromKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCloudEventsFromKeysResponse) ProtoMessage() {}

func (x *ListCloudEventsFromKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fetch_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCloudEventsFromKeysResponse.ProtoReflect.Descriptor instead.
func (*ListCloudEventsFromKeysResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fetch_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListCloudEventsFromKeysResponse) GetCloudEvents() []*CloudEvent {
	if x != nil {
		return x.CloudEvents
	}
	return nil
}

var File_pkg_grpc_fetch_api_proto protoreflect.FileDescriptor

var file_pkg_grpc_fetch_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68,
	0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x04, 0x0a,
	0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x30,
	0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72,
	0x12, 0x32, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x62, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x5f, 0x61, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x41, 0x73, 0x63, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x64, 0x61, 0x74,
	0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x34, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x12, 0x38, 0x0a, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0x5c, 0x0a, 0x12, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x34, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x49, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x51, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5a, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x55, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x56, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x5d,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x54, 0x0a,
	0x17, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x3f, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x4b, 0x65, 0x79, 0x73, 0x22, 0x5c, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0xbf, 0x03, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x17,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x46,
	0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x44, 0x49, 0x4d, 0x4f, 0x2d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_fetch_api_proto_rawDescOnce sync.Once
	file_pkg_grpc_fetch_api_proto_rawDescData = file_pkg_grpc_fetch_api_proto_rawDesc
)

func file_pkg_grpc_fetch_api_proto_rawDescGZIP() []byte {
	file_pkg_grpc_fetch_api_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_fetch_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_fetch_api_proto_rawDescData)
	})
	return file_pkg_grpc_fetch_api_proto_rawDescData
}

var file_pkg_grpc_fetch_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_grpc_fetch_api_proto_goTypes = []any{
	(*SearchOptions)(nil),                   // 0: grpc.SearchOptions
	(*CloudEventMetadata)(nil),              // 1: grpc.CloudEventMetadata
	(*GetLatestMetadataRequest)(nil),        // 2: grpc.GetLatestMetadataRequest
	(*GetLatestMetadataResponse)(nil),       // 3: grpc.GetLatestMetadataResponse
	(*ListMetadataRequest)(nil),             // 4: grpc.ListMetadataRequest
	(*ListMetadataResponse)(nil),            // 5: grpc.ListMetadataResponse
	(*GetLatestCloudEventRequest)(nil),      // 6: grpc.GetLatestCloudEventRequest
	(*GetLatestCloudEventResponse)(nil),     // 7: grpc.GetLatestCloudEventResponse
	(*ListCloudEventsRequest)(nil),          // 8: grpc.ListCloudEventsRequest
	(*ListCloudEventsResponse)(nil),         // 9: grpc.ListCloudEventsResponse
	(*ListCloudEventsFromKeysRequest)(nil),  // 10: grpc.ListCloudEventsFromKeysRequest
	(*ListCloudEventsFromKeysResponse)(nil), // 11: grpc.ListCloudEventsFromKeysResponse
	(*timestamppb.Timestamp)(nil),           // 12: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),            // 13: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil),          // 14: google.protobuf.StringValue
	(*CloudEventHeader)(nil),                // 15: cloudevent.CloudEventHeader
	(*CloudEvent)(nil),                      // 16: cloudevent.CloudEvent
}
var file_pkg_grpc_fetch_api_proto_depIdxs = []int32{
	12, // 0: grpc.SearchOptions.after:type_name -> google.protobuf.Timestamp
	12, // 1: grpc.SearchOptions.before:type_name -> google.protobuf.Timestamp
	13, // 2: grpc.SearchOptions.timestamp_asc:type_name -> google.protobuf.BoolValue
	14, // 3: grpc.SearchOptions.type:type_name -> google.protobuf.StringValue
	14, // 4: grpc.SearchOptions.data_version:type_name -> google.protobuf.StringValue
	14, // 5: grpc.SearchOptions.subject:type_name -> google.protobuf.StringValue
	14, // 6: grpc.SearchOptions.source:type_name -> google.protobuf.StringValue
	14, // 7: grpc.SearchOptions.producer:type_name -> google.protobuf.StringValue
	14, // 8: grpc.SearchOptions.optional:type_name -> google.protobuf.StringValue
	15, // 9: grpc.CloudEventMetadata.header:type_name -> cloudevent.CloudEventHeader
	0,  // 10: grpc.GetLatestMetadataRequest.options:type_name -> grpc.SearchOptions
	1,  // 11: grpc.GetLatestMetadataResponse.metadata:type_name -> grpc.CloudEventMetadata
	0,  // 12: grpc.ListMetadataRequest.options:type_name -> grpc.SearchOptions
	1,  // 13: grpc.ListMetadataResponse.metadata_list:type_name -> grpc.CloudEventMetadata
	0,  // 14: grpc.GetLatestCloudEventRequest.options:type_name -> grpc.SearchOptions
	16, // 15: grpc.GetLatestCloudEventResponse.cloud_event:type_name -> cloudevent.CloudEvent
	0,  // 16: grpc.ListCloudEventsRequest.options:type_name -> grpc.SearchOptions
	16, // 17: grpc.ListCloudEventsResponse.cloud_events:type_name -> cloudevent.CloudEvent
	16, // 18: grpc.ListCloudEventsFromKeysResponse.cloud_events:type_name -> cloudevent.CloudEvent
	2,  // 19: grpc.FetchService.GetLatestMetadata:input_type -> grpc.GetLatestMetadataRequest
	4,  // 20: grpc.FetchService.ListMetadata:input_type -> grpc.ListMetadataRequest
	6,  // 21: grpc.FetchService.GetLatestCloudEvent:input_type -> grpc.GetLatestCloudEventRequest
	8,  // 22: grpc.FetchService.ListCloudEvents:input_type -> grpc.ListCloudEventsRequest
	10, // 23: grpc.FetchService.ListCloudEventsFromKeys:input_type -> grpc.ListCloudEventsFromKeysRequest
	3,  // 24: grpc.FetchService.GetLatestMetadata:output_type -> grpc.GetLatestMetadataResponse
	5,  // 25: grpc.FetchService.ListMetadata:output_type -> grpc.ListMetadataResponse
	7,  // 26: grpc.FetchService.GetLatestCloudEvent:output_type -> grpc.GetLatestCloudEventResponse
	9,  // 27: grpc.FetchService.ListCloudEvents:output_type -> grpc.ListCloudEventsResponse
	11, // 28: grpc.FetchService.ListCloudEventsFromKeys:output_type -> grpc.ListCloudEventsFromKeysResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_grpc_fetch_api_proto_init() }
func file_pkg_grpc_fetch_api_proto_init() {
	if File_pkg_grpc_fetch_api_proto != nil {
		return
	}
	file_pkg_grpc_cloudevent_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_fetch_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CloudEventMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestCloudEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestCloudEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListCloudEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListCloudEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListCloudEventsFromKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fetch_api_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListCloudEventsFromKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_fetch_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_fetch_api_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_fetch_api_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_fetch_api_proto_msgTypes,
	}.Build()
	File_pkg_grpc_fetch_api_proto = out.File
	file_pkg_grpc_fetch_api_proto_rawDesc = nil
	file_pkg_grpc_fetch_api_proto_goTypes = nil
	file_pkg_grpc_fetch_api_proto_depIdxs = nil
}
