// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: pkg/grpc/fetch-api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IndexRepoServiceClient is the client API for IndexRepoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexRepoServiceClient interface {
	// GetLatestFileName returns the latest filename for the given options
	GetLatestFileName(ctx context.Context, in *GetLatestFileNameRequest, opts ...grpc.CallOption) (*GetLatestFileNameResponse, error)
	// GetFileNames fetches and returns the list of filenames that match the specified options,
	GetFileNames(ctx context.Context, in *GetFileNamesRequest, opts ...grpc.CallOption) (*GetFileNamesResponse, error)
	// GetLatestData fetches and returns the latest file that matches the specified options
	GetLatestFile(ctx context.Context, in *GetLatestFileRequest, opts ...grpc.CallOption) (*GetLatestFileResponse, error)
	// GetFiles fetches and returns the list of files that match the specified options
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
}

type indexRepoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexRepoServiceClient(cc grpc.ClientConnInterface) IndexRepoServiceClient {
	return &indexRepoServiceClient{cc}
}

func (c *indexRepoServiceClient) GetLatestFileName(ctx context.Context, in *GetLatestFileNameRequest, opts ...grpc.CallOption) (*GetLatestFileNameResponse, error) {
	out := new(GetLatestFileNameResponse)
	err := c.cc.Invoke(ctx, "/grpc.IndexRepoService/GetLatestFileName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexRepoServiceClient) GetFileNames(ctx context.Context, in *GetFileNamesRequest, opts ...grpc.CallOption) (*GetFileNamesResponse, error) {
	out := new(GetFileNamesResponse)
	err := c.cc.Invoke(ctx, "/grpc.IndexRepoService/GetFileNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexRepoServiceClient) GetLatestFile(ctx context.Context, in *GetLatestFileRequest, opts ...grpc.CallOption) (*GetLatestFileResponse, error) {
	out := new(GetLatestFileResponse)
	err := c.cc.Invoke(ctx, "/grpc.IndexRepoService/GetLatestFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexRepoServiceClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, "/grpc.IndexRepoService/GetFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexRepoServiceServer is the server API for IndexRepoService service.
// All implementations must embed UnimplementedIndexRepoServiceServer
// for forward compatibility
type IndexRepoServiceServer interface {
	// GetLatestFileName returns the latest filename for the given options
	GetLatestFileName(context.Context, *GetLatestFileNameRequest) (*GetLatestFileNameResponse, error)
	// GetFileNames fetches and returns the list of filenames that match the specified options,
	GetFileNames(context.Context, *GetFileNamesRequest) (*GetFileNamesResponse, error)
	// GetLatestData fetches and returns the latest file that matches the specified options
	GetLatestFile(context.Context, *GetLatestFileRequest) (*GetLatestFileResponse, error)
	// GetFiles fetches and returns the list of files that match the specified options
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	mustEmbedUnimplementedIndexRepoServiceServer()
}

// UnimplementedIndexRepoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIndexRepoServiceServer struct {
}

func (UnimplementedIndexRepoServiceServer) GetLatestFileName(context.Context, *GetLatestFileNameRequest) (*GetLatestFileNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestFileName not implemented")
}
func (UnimplementedIndexRepoServiceServer) GetFileNames(context.Context, *GetFileNamesRequest) (*GetFileNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileNames not implemented")
}
func (UnimplementedIndexRepoServiceServer) GetLatestFile(context.Context, *GetLatestFileRequest) (*GetLatestFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestFile not implemented")
}
func (UnimplementedIndexRepoServiceServer) GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedIndexRepoServiceServer) mustEmbedUnimplementedIndexRepoServiceServer() {}

// UnsafeIndexRepoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexRepoServiceServer will
// result in compilation errors.
type UnsafeIndexRepoServiceServer interface {
	mustEmbedUnimplementedIndexRepoServiceServer()
}

func RegisterIndexRepoServiceServer(s grpc.ServiceRegistrar, srv IndexRepoServiceServer) {
	s.RegisterService(&IndexRepoService_ServiceDesc, srv)
}

func _IndexRepoService_GetLatestFileName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestFileNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexRepoServiceServer).GetLatestFileName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IndexRepoService/GetLatestFileName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexRepoServiceServer).GetLatestFileName(ctx, req.(*GetLatestFileNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexRepoService_GetFileNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexRepoServiceServer).GetFileNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IndexRepoService/GetFileNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexRepoServiceServer).GetFileNames(ctx, req.(*GetFileNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexRepoService_GetLatestFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexRepoServiceServer).GetLatestFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IndexRepoService/GetLatestFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexRepoServiceServer).GetLatestFile(ctx, req.(*GetLatestFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexRepoService_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexRepoServiceServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IndexRepoService/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexRepoServiceServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexRepoService_ServiceDesc is the grpc.ServiceDesc for IndexRepoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexRepoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.IndexRepoService",
	HandlerType: (*IndexRepoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestFileName",
			Handler:    _IndexRepoService_GetLatestFileName_Handler,
		},
		{
			MethodName: "GetFileNames",
			Handler:    _IndexRepoService_GetFileNames_Handler,
		},
		{
			MethodName: "GetLatestFile",
			Handler:    _IndexRepoService_GetLatestFile_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _IndexRepoService_GetFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/fetch-api.proto",
}
