package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"errors"

	"github.com/DIMO-Network/cloudevent"
	"github.com/DIMO-Network/fetch-api/internal/fetch"
	"github.com/DIMO-Network/fetch-api/internal/graph/model"
)

// Header is the resolver for the header field. Returns a pointer into the wrapped event; no copy.
func (r *cloudEventResolver) Header(ctx context.Context, obj *CloudEventWrapper) (*cloudevent.CloudEventHeader, error) {
	if obj == nil || obj.Raw == nil {
		return nil, nil
	}
	return &obj.Raw.CloudEventHeader, nil
}

// Data is the resolver for the data field. Returns raw JSON so it is serialized as an object, not an escaped string.
// Zero-copy: the underlying bytes are only read during serialization.
func (r *cloudEventResolver) Data(ctx context.Context, obj *CloudEventWrapper) (RawJSON, error) {
	if obj == nil || obj.Raw == nil || len(obj.Raw.Data) == 0 {
		return nil, nil
	}
	return RawJSON(obj.Raw.Data), nil
}

// DataBase64 is the resolver for the dataBase64 field. Returns pointer into wrapped event when present.
func (r *cloudEventResolver) DataBase64(ctx context.Context, obj *CloudEventWrapper) (*string, error) {
	if obj == nil || obj.Raw == nil || obj.Raw.DataBase64 == "" {
		return nil, nil
	}
	return &obj.Raw.DataBase64, nil
}

// LatestIndex is the resolver for the latestIndex field.
func (r *queryResolver) LatestIndex(ctx context.Context, did string, filter *model.CloudEventFilter) (*model.CloudEventIndex, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	return indexToModel(idx), nil
}

// Indexes is the resolver for the indexes field.
func (r *queryResolver) Indexes(ctx context.Context, did string, limit *int, filter *model.CloudEventFilter) ([]*model.CloudEventIndex, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventIndexList, nil
		}
		return nil, err
	}
	out := make([]*model.CloudEventIndex, len(list))
	for i := range list {
		out[i] = indexToModel(list[i])
	}
	return out, nil
}

// LatestCloudEvent is the resolver for the latestCloudEvent field.
func (r *queryResolver) LatestCloudEvent(ctx context.Context, did string, filter *model.CloudEventFilter) (*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	ce, err := fetch.GetCloudEventFromIndex(ctx, r.EventService, &idx, r.Buckets)
	if err != nil {
		return nil, err
	}
	return &CloudEventWrapper{Raw: &ce}, nil
}

// CloudEvents is the resolver for the cloudEvents field.
func (r *queryResolver) CloudEvents(ctx context.Context, did string, limit *int, filter *model.CloudEventFilter) ([]*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventList, nil
		}
		return nil, err
	}
	events, err := fetch.ListCloudEventsFromIndexes(ctx, r.EventService, list, r.Buckets)
	if err != nil {
		return nil, err
	}
	out := make([]*CloudEventWrapper, len(events))
	for i := range events {
		out[i] = &CloudEventWrapper{Raw: &events[i]}
	}
	return out, nil
}

// AvailableEvents is the resolver for the availableEvents field.
func (r *queryResolver) AvailableEvents(ctx context.Context, did string, filter *model.CloudEventFilter) ([]*model.EventTypeSummary, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	summaries, err := r.EventService.GetEventTypeSummaries(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := make([]*model.EventTypeSummary, len(summaries))
	for i, s := range summaries {
		out[i] = &model.EventTypeSummary{
			Type:      s.Type,
			Count:     int(s.Count),
			FirstSeen: s.FirstSeen,
			LastSeen:  s.LastSeen,
		}
	}
	return out, nil
}

// CloudEvent returns CloudEventResolver implementation.
func (r *Resolver) CloudEvent() CloudEventResolver { return &cloudEventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type cloudEventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
