package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"

	"github.com/DIMO-Network/cloudevent"
	"github.com/DIMO-Network/fetch-api/internal/fetch"
	"github.com/DIMO-Network/fetch-api/internal/graph/model"
)

// LatestIndex is the resolver for the latestIndex field.
func (r *queryResolver) LatestIndex(ctx context.Context, tokenID int, filter *model.CloudEventFilter) (*model.CloudEventIndex, error) {
	opts, err := r.requireVehicleOpts(ctx, tokenID, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	return indexToModel(idx), nil
}

// Indexes is the resolver for the indexes field.
func (r *queryResolver) Indexes(ctx context.Context, tokenID int, limit *int, filter *model.CloudEventFilter) ([]*model.CloudEventIndex, error) {
	opts, err := r.requireVehicleOpts(ctx, tokenID, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventIndexList, nil
		}
		return nil, err
	}
	out := make([]*model.CloudEventIndex, len(list))
	for i := range list {
		out[i] = indexToModel(list[i])
	}
	return out, nil
}

// LatestCloudEvent is the resolver for the latestCloudEvent field.
func (r *queryResolver) LatestCloudEvent(ctx context.Context, tokenID int, filter *model.CloudEventFilter) (*cloudevent.CloudEvent[json.RawMessage], error) {
	opts, err := r.requireVehicleOpts(ctx, tokenID, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	ce, err := fetch.GetCloudEventFromIndex(ctx, r.EventService, idx, r.Buckets)
	if err != nil {
		return nil, err
	}
	return &ce, nil
}

// CloudEvents is the resolver for the cloudEvents field.
func (r *queryResolver) CloudEvents(ctx context.Context, tokenID int, limit *int, filter *model.CloudEventFilter) ([]*cloudevent.CloudEvent[json.RawMessage], error) {
	opts, err := r.requireVehicleOpts(ctx, tokenID, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventList, nil
		}
		return nil, err
	}
	events, err := fetch.ListCloudEventsFromIndexes(ctx, r.EventService, list, r.Buckets)
	if err != nil {
		return nil, err
	}
	out := make([]*cloudevent.RawEvent, len(events))
	for i := range events {
		out[i] = &events[i]
	}
	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
