package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"errors"

	"github.com/DIMO-Network/cloudevent"
	"github.com/DIMO-Network/fetch-api/internal/fetch"
	"github.com/DIMO-Network/fetch-api/internal/graph/model"
	"github.com/DIMO-Network/fetch-api/pkg/eventrepo"
	fetchgrpc "github.com/DIMO-Network/fetch-api/pkg/grpc"
)

// Header is the resolver for the header field. Returns a pointer into the wrapped event; no copy.
func (r *cloudEventResolver) Header(ctx context.Context, obj *CloudEventWrapper) (*cloudevent.CloudEventHeader, error) {
	if obj == nil || obj.Raw == nil {
		return nil, nil
	}
	return &obj.Raw.CloudEventHeader, nil
}

// Data is the resolver for the data field. Returns raw JSON so it is serialized as an object, not an escaped string.
// Zero-copy: the underlying bytes are only read during serialization.
func (r *cloudEventResolver) Data(ctx context.Context, obj *CloudEventWrapper) (RawJSON, error) {
	if obj == nil || obj.Raw == nil || len(obj.Raw.Data) == 0 {
		return nil, nil
	}
	return RawJSON(obj.Raw.Data), nil
}

// DataBase64 is the resolver for the dataBase64 field. Returns pointer into wrapped event when present.
func (r *cloudEventResolver) DataBase64(ctx context.Context, obj *CloudEventWrapper) (*string, error) {
	if obj == nil || obj.Raw == nil || obj.Raw.DataBase64 == "" {
		return nil, nil
	}
	return &obj.Raw.DataBase64, nil
}

// PresignedUrl is the resolver for the presignedUrl field.
// Returns a short-lived pre-signed S3 URL for large single-file events.
func (r *cloudEventResolver) PresignedUrl(ctx context.Context, obj *CloudEventWrapper) (*string, error) {
	if obj == nil || obj.PresignedURL == "" {
		return nil, nil
	}
	return &obj.PresignedURL, nil
}

// LatestIndex is the resolver for the latestIndex field.
func (r *queryResolver) LatestIndex(ctx context.Context, did string, filter *model.CloudEventFilter) (*model.CloudEventIndex, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	return indexToModel(idx), nil
}

// Indexes is the resolver for the indexes field.
func (r *queryResolver) Indexes(ctx context.Context, did string, limit *int, filter *model.CloudEventFilter) ([]*model.CloudEventIndex, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventIndexList, nil
		}
		return nil, err
	}
	out := make([]*model.CloudEventIndex, len(list))
	for i := range list {
		out[i] = indexToModel(list[i])
	}
	return out, nil
}

// LatestCloudEvent is the resolver for the latestCloudEvent field.
func (r *queryResolver) LatestCloudEvent(ctx context.Context, did string, filter *model.CloudEventFilter) (*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	idx, err := r.EventService.GetLatestIndex(ctx, opts)
	if err != nil {
		return nil, err
	}
	if eventrepo.IsSingleEventRef(idx.Data.Key) {
		url, err := r.presignSingleEvent(ctx, idx.Data.Key)
		if err != nil {
			return nil, err
		}
		hdr := idx.CloudEventHeader
		hdr.Tags = fetchgrpc.TagsOrEmpty(hdr.Tags)
		return &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, PresignedURL: url}, nil
	}
	ce, err := fetch.GetCloudEventFromIndex(ctx, r.EventService, &idx, r.Buckets)
	if err != nil {
		return nil, err
	}
	return &CloudEventWrapper{Raw: &ce}, nil
}

// CloudEvents is the resolver for the cloudEvents field.
func (r *queryResolver) CloudEvents(ctx context.Context, did string, limit *int, filter *model.CloudEventFilter) ([]*CloudEventWrapper, error) {
	opts, err := r.requireSubjectOptsByDID(ctx, did, filter)
	if err != nil {
		return nil, err
	}
	list, err := r.EventService.ListIndexes(ctx, resolveLimit(limit), opts)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return emptyCloudEventList, nil
		}
		return nil, err
	}

	out := make([]*CloudEventWrapper, len(list))

	// Separate single-event refs (presign only) from regular refs (fetch from S3).
	var fetchIndexes []cloudevent.CloudEvent[eventrepo.ObjectInfo]
	var fetchPositions []int
	for i, idx := range list {
		if eventrepo.IsSingleEventRef(idx.Data.Key) {
			url, err := r.presignSingleEvent(ctx, idx.Data.Key)
			if err != nil {
				return nil, err
			}
			hdr := idx.CloudEventHeader
			hdr.Tags = fetchgrpc.TagsOrEmpty(hdr.Tags)
			out[i] = &CloudEventWrapper{Raw: &cloudevent.RawEvent{CloudEventHeader: hdr}, PresignedURL: url}
		} else {
			fetchIndexes = append(fetchIndexes, idx)
			fetchPositions = append(fetchPositions, i)
		}
	}

	if len(fetchIndexes) > 0 {
		events, err := fetch.ListCloudEventsFromIndexes(ctx, r.EventService, fetchIndexes, r.Buckets)
		if err != nil {
			return nil, err
		}
		for i, pos := range fetchPositions {
			out[pos] = &CloudEventWrapper{Raw: &events[i]}
		}
	}

	return out, nil
}

// CloudEvent returns CloudEventResolver implementation.
func (r *Resolver) CloudEvent() CloudEventResolver { return &cloudEventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type cloudEventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
