// Code generated by mcpgen. DO NOT EDIT.
package graph

import (
	"github.com/DIMO-Network/server-garage/pkg/mcpserver"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func boolPtr(b bool) *bool { return &b }

var MCPTools = []mcpserver.ToolDefinition{
	{
		Name:        "fetch_get_latest_index",
		Description: "Get the latest CloudEvent index entry (header + storage key) for a DID-scoped subject, optionally filtered by event type, source, producer, or time range. Returns metadata only — use fetch_get_latest_cloud_event for the full payload.",
		Args: []mcpserver.ArgDefinition{
			{Name: "did", Type: "string", Description: "did (String!, required)", Required: true, ItemsType: ""},
			{Name: "filter", Type: "object", Description: "filter (CloudEventFilter, optional)", Required: false, ItemsType: ""},
			{Name: "includeDeleted", Type: "boolean", Description: "includeDeleted (Boolean, optional)", Required: false, ItemsType: ""},
		},
		Query: "query($did: String!, $filter: CloudEventFilter, $includeDeleted: Boolean) { latestIndex(did: $did, filter: $filter, includeDeleted: $includeDeleted) { header { type source subject id time producer dataversion } indexKey } }",
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:    true,
			DestructiveHint: boolPtr(false),
			OpenWorldHint:   boolPtr(false),
			IdempotentHint:  true,
		},
	},
	{
		Name:        "fetch_list_indexes",
		Description: "List CloudEvent index entries for a DID-scoped subject, optionally filtered and limited (default 10). Returns headers + storage keys without payloads — cheaper than fetch_list_cloud_events when exploring.",
		Args: []mcpserver.ArgDefinition{
			{Name: "did", Type: "string", Description: "did (String!, required)", Required: true, ItemsType: ""},
			{Name: "limit", Type: "integer", Description: "limit (Int, optional)", Required: false, ItemsType: ""},
			{Name: "filter", Type: "object", Description: "filter (CloudEventFilter, optional)", Required: false, ItemsType: ""},
			{Name: "includeDeleted", Type: "boolean", Description: "includeDeleted (Boolean, optional)", Required: false, ItemsType: ""},
		},
		Query: "query($did: String!, $limit: Int, $filter: CloudEventFilter, $includeDeleted: Boolean) { indexes(did: $did, limit: $limit, filter: $filter, includeDeleted: $includeDeleted) { header { type source subject id time producer } indexKey } }",
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:    true,
			DestructiveHint: boolPtr(false),
			OpenWorldHint:   boolPtr(false),
			IdempotentHint:  true,
		},
	},
	{
		Name:        "fetch_get_latest_cloud_event",
		Description: "Get the latest full CloudEvent (header + JSON payload) for a DID-scoped subject, optionally filtered. Returns dataUrl (presigned S3 link) for large binary payloads instead of inlining them.",
		Args: []mcpserver.ArgDefinition{
			{Name: "did", Type: "string", Description: "did (String!, required)", Required: true, ItemsType: ""},
			{Name: "filter", Type: "object", Description: "filter (CloudEventFilter, optional)", Required: false, ItemsType: ""},
			{Name: "includeDeleted", Type: "boolean", Description: "includeDeleted (Boolean, optional)", Required: false, ItemsType: ""},
		},
		Query: "query($did: String!, $filter: CloudEventFilter, $includeDeleted: Boolean) { latestCloudEvent(did: $did, filter: $filter, includeDeleted: $includeDeleted) { header { type source subject id time producer } data dataUrl } }",
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:    true,
			DestructiveHint: boolPtr(false),
			OpenWorldHint:   boolPtr(false),
			IdempotentHint:  true,
		},
	},
	{
		Name:        "fetch_list_cloud_events",
		Description: "List full CloudEvents (headers + JSON payloads) for a DID-scoped subject, optionally filtered and limited (default 10). Large binary payloads are returned as presigned S3 URLs via dataUrl instead of inlined data.",
		Args: []mcpserver.ArgDefinition{
			{Name: "did", Type: "string", Description: "did (String!, required)", Required: true, ItemsType: ""},
			{Name: "limit", Type: "integer", Description: "limit (Int, optional)", Required: false, ItemsType: ""},
			{Name: "filter", Type: "object", Description: "filter (CloudEventFilter, optional)", Required: false, ItemsType: ""},
			{Name: "includeDeleted", Type: "boolean", Description: "includeDeleted (Boolean, optional)", Required: false, ItemsType: ""},
		},
		Query: "query($did: String!, $limit: Int, $filter: CloudEventFilter, $includeDeleted: Boolean) { cloudEvents(did: $did, limit: $limit, filter: $filter, includeDeleted: $includeDeleted) { header { type source subject id time producer } data dataUrl } }",
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:    true,
			DestructiveHint: boolPtr(false),
			OpenWorldHint:   boolPtr(false),
			IdempotentHint:  true,
		},
	},
	{
		Name:        "fetch_list_available_event_types",
		Description: "Summarize the CloudEvent types present for a DID-scoped subject. Returns each type with its count, firstSeen, and lastSeen timestamps — useful for discovering what kinds of events exist before querying them.",
		Args: []mcpserver.ArgDefinition{
			{Name: "did", Type: "string", Description: "did (String!, required)", Required: true, ItemsType: ""},
			{Name: "filter", Type: "object", Description: "filter (CloudEventFilter, optional)", Required: false, ItemsType: ""},
			{Name: "includeDeleted", Type: "boolean", Description: "includeDeleted (Boolean, optional)", Required: false, ItemsType: ""},
		},
		Query: "query($did: String!, $filter: CloudEventFilter, $includeDeleted: Boolean) { availableCloudEventTypes(did: $did, filter: $filter, includeDeleted: $includeDeleted) { type count firstSeen lastSeen } }",
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:    true,
			DestructiveHint: boolPtr(false),
			OpenWorldHint:   boolPtr(false),
			IdempotentHint:  true,
		},
	},
}

var CondensedSchema = "scalar JSON  # Arbitrary JSON value; serialized as raw JSON (object/array), not an escaped string.\nscalar Time  # A point in time, encoded per RFC-3339.\n\ntype Query {\n  \"Latest cloud event index matching filters. Tombstoned attestations are hidden from the result by default; pass includeDeleted: true to disable tombstone suppression.\"\n  latestIndex(did: String!, filter: CloudEventFilter, includeDeleted: Boolean = false): CloudEventIndex!\n\n  indexes(did: String!, limit: Int = 10, filter: CloudEventFilter, includeDeleted: Boolean = false): [CloudEventIndex!]!\n  \"Latest full cloud event. Tombstoned attestations are hidden from the result by default; pass includeDeleted: true to disable tombstone suppression.\"\n  latestCloudEvent(did: String!, filter: CloudEventFilter, includeDeleted: Boolean = false): CloudEvent!\n\n  cloudEvents(did: String!, limit: Int = 10, filter: CloudEventFilter, includeDeleted: Boolean = false): [CloudEvent!]!\n  availableCloudEventTypes(did: String!, filter: CloudEventFilter, includeDeleted: Boolean = false): [CloudEventTypeSummary!]!\n}\n\ntype CloudEvent { header: CloudEventHeader!, data: JSON, dataBase64: String, dataUrl: String }\n\ninput CloudEventFilter { id: String, type: String, types: [String!], dataversion: String, source: String, producer: String, before: Time, after: Time }\n\ntype CloudEventHeader { specversion: String!, type: String!, source: String!, subject: String!, id: String!, time: Time!, datacontenttype: String, dataschema: String, dataversion: String, producer: String!, signature: String, raweventid: String, tags: [String!]! }\n\ntype CloudEventIndex { header: CloudEventHeader!, indexKey: String! }\n\ntype CloudEventTypeSummary { type: String!, count: Int!, firstSeen: Time!, lastSeen: Time! }\n"
